language: ruby
rvm:
  - 1.8.7
  - 2.0.0

before_script: |
  hg clone https://code.google.com/p/vim/
  cd vim
  ./configure --with-features=huge --enable-rubyinterp
  make
  sudo make install
  cd -
  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

script: |
  test/run !
